-- MySQL Script generated by MySQL Workbench
-- 08/24/15 17:08:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blog` ;

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`users` ;

CREATE TABLE IF NOT EXISTS `blog`.`users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(50) NULL COMMENT '',
  `password` VARCHAR(100) NULL COMMENT '',
  `first_name` VARCHAR(30) NULL COMMENT '',
  `last_name` VARCHAR(30) NULL COMMENT '',
  `email` VARCHAR(50) NULL COMMENT '',
  `phone` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`posts` ;

CREATE TABLE IF NOT EXISTS `blog`.`posts` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `users_id` INT(11) UNSIGNED NOT NULL COMMENT '',
  `title` VARCHAR(100) NULL COMMENT '',
  `image` VARCHAR(255) NULL COMMENT '',
  `intro` TEXT NULL COMMENT '',
  `content` TEXT NULL COMMENT '',
  `created_date` INT(10) UNSIGNED NULL COMMENT '',
  `active` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  `status` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_posts_users_idx` (`users_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`comments` ;

CREATE TABLE IF NOT EXISTS `blog`.`comments` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `users_id` INT(11) UNSIGNED NOT NULL COMMENT '',
  `posts_id` INT(11) UNSIGNED NOT NULL COMMENT '',
  `posts_users_id` INT(11) UNSIGNED NOT NULL COMMENT '',
  `content` TEXT NULL COMMENT '',
  `created_date` INT(10) UNSIGNED NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_comments_users1_idx` (`users_id` ASC)  COMMENT '',
  INDEX `fk_comments_posts1_idx` (`posts_id` ASC, `posts_users_id` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
