# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 26 Aug 2015 07:37:04 +0000
*               @ALL          1
*               @user         8
