<?php
/*
 * Siteexport Cron Job Configuration
 * Auto-generated by siteexport
 * Run for user: admin
 */

// Required to set the HTTP_HOST which is usually not set in CLI Environments 
$_SERVER['HTTP_HOST'] = "doc.app";

// This is not the nice way to inject another ROOT-URL, but we do not want to modify other stuff. 
if(!defined('DOKU_URL')) define('DOKU_URL', "http://doc.app/");


// end of auto-generated content