<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Thu, 27 Aug 2015 04:22:09 +0000
 */

$conf['title'] = 'Laravel Documentation';
$conf['start'] = 'laravel';
$conf['sidebar'] = 'indexmenu';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['indexmenu']['skip_index'] = '/(wiki)/';
$conf['plugin']['indexmenu']['skip_file'] = '/(indexmenu)/';
$conf['plugin']['siteexport']['allowallusers'] = 1;
$conf['plugin']['siteexport']['skipacl'] = 1;

// end auto-generated content
